#!/bin/bash
# Assemble Modular Logstash Configs
# Combines input, filter, and output modules into a single deployable config file
#
# Usage: ./assemble-config.sh <output-type> [destination]
# Example: ./assemble-config.sh splunk-hec
# Example: ./assemble-config.sh azure-log-ingestion ./custom-output.conf
#
# Available output types:
#   splunk-hec          - Splunk HTTP Event Collector
#   azure-log-ingestion - Azure Log Analytics via DCR
#   dynatrace-metrics   - Dynatrace Metrics Ingest (MINT protocol)
#   dynatrace-logs      - Dynatrace Logs Ingest (JSON)
#   dynatrace           - Dynatrace Combined (metrics + logs)

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_DIR="$(dirname "$SCRIPT_DIR")"

OUTPUT_TYPE="${1:-}"
DEST="${2:-}"

# Color output helpers
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

print_usage() {
    echo "Usage: $0 <output-type> [destination]"
    echo ""
    echo "Available output types:"
    echo "  splunk-hec          - Splunk HTTP Event Collector"
    echo "  azure-log-ingestion - Azure Log Analytics via DCR"
    echo "  dynatrace-metrics   - Dynatrace Metrics Ingest (MINT protocol)"
    echo "  dynatrace-logs      - Dynatrace Logs Ingest (JSON)"
    echo "  dynatrace           - Dynatrace Combined (metrics + logs)"
    echo ""
    echo "Examples:"
    echo "  $0 splunk-hec"
    echo "  $0 dynatrace"
    echo "  $0 azure-log-ingestion ./custom-output.conf"
}

if [[ -z "$OUTPUT_TYPE" ]]; then
    echo -e "${RED}Error: Output type is required${NC}"
    print_usage
    exit 1
fi

# Validate output type exists
if [[ ! -d "$CONFIG_DIR/outputs/$OUTPUT_TYPE" ]]; then
    echo -e "${RED}Error: Unknown output type '$OUTPUT_TYPE'${NC}"
    echo "Available types:"
    ls -1 "$CONFIG_DIR/outputs/" 2>/dev/null || echo "  (none found)"
    exit 1
fi

if [[ ! -f "$CONFIG_DIR/outputs/$OUTPUT_TYPE/output.conf" ]]; then
    echo -e "${RED}Error: Output config not found at $CONFIG_DIR/outputs/$OUTPUT_TYPE/output.conf${NC}"
    exit 1
fi

# Set default destination if not provided
if [[ -z "$DEST" ]]; then
    mkdir -p "$CONFIG_DIR/assembled"
    DEST="$CONFIG_DIR/assembled/${OUTPUT_TYPE}-full.conf"
fi

echo -e "${YELLOW}Assembling Logstash config for: $OUTPUT_TYPE${NC}"
echo "Output file: $DEST"
echo ""

# Create/clear the output file with a header
cat > "$DEST" << EOF
# Aviatrix Log Integration Engine - Assembled Configuration
# Output Type: $OUTPUT_TYPE
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# This file was automatically generated by assemble-config.sh
# Do not edit directly - modify the source modules instead:
#   - logstash-configs/inputs/
#   - logstash-configs/filters/
#   - logstash-configs/outputs/$OUTPUT_TYPE/
#
# To regenerate: ./scripts/assemble-config.sh $OUTPUT_TYPE

EOF

# Assemble inputs
echo -e "${GREEN}Adding inputs...${NC}"
echo "# ============================================================================" >> "$DEST"
echo "# INPUT CONFIGURATION" >> "$DEST"
echo "# ============================================================================" >> "$DEST"
echo "" >> "$DEST"

for input_file in "$CONFIG_DIR/inputs/"*.conf; do
    if [[ -f "$input_file" ]]; then
        echo "  - $(basename "$input_file")"
        cat "$input_file" >> "$DEST"
        echo "" >> "$DEST"
    fi
done

# Assemble filters (in sorted order)
echo -e "${GREEN}Adding filters...${NC}"
echo "# ============================================================================" >> "$DEST"
echo "# FILTER CONFIGURATION" >> "$DEST"
echo "# ============================================================================" >> "$DEST"
echo "" >> "$DEST"

for filter_file in $(ls "$CONFIG_DIR/filters/"*.conf 2>/dev/null | sort); do
    if [[ -f "$filter_file" ]]; then
        echo "  - $(basename "$filter_file")"
        cat "$filter_file" >> "$DEST"
        echo "" >> "$DEST"
    fi
done

# Assemble output
echo -e "${GREEN}Adding output ($OUTPUT_TYPE)...${NC}"
echo "# ============================================================================" >> "$DEST"
echo "# OUTPUT CONFIGURATION ($OUTPUT_TYPE)" >> "$DEST"
echo "# ============================================================================" >> "$DEST"
echo "" >> "$DEST"

cat "$CONFIG_DIR/outputs/$OUTPUT_TYPE/output.conf" >> "$DEST"

# Copy docker_run.tftpl to assembled directory (needed by Terraform deployments)
DEST_DIR="$(dirname "$DEST")"
if [[ -f "$CONFIG_DIR/outputs/$OUTPUT_TYPE/docker_run.tftpl" ]]; then
    echo -e "${GREEN}Copying docker_run.tftpl...${NC}"
    cp "$CONFIG_DIR/outputs/$OUTPUT_TYPE/docker_run.tftpl" "$DEST_DIR/docker_run.tftpl"
    echo "  - docker_run.tftpl → $DEST_DIR/docker_run.tftpl"
fi

echo ""
echo -e "${GREEN}Assembly complete!${NC}"
echo "Output written to: $DEST"
echo ""

# Show file size
FILE_SIZE=$(wc -l < "$DEST")
echo "Total lines: $FILE_SIZE"
